# Package versions.
FLEX_VERSION=2.6.4
ZLIB_VERSION=1.3.1
BZIP2_VERSION=1.0.8
BASH_VERSION=5.3
E2FSPROGS_VERSION=1.47.2
LIBUUID_VERSION=1.0.3
UTIL_LINUX_MAJOR_VERSION=2.41
UTIL_LINUX_VERSION=2.41
SHADOW_VERSION=4.18.0
SED_VERSION=4.9
GMP_VERSION=6.3.0
MPC_VERSION=1.3.1
NCURSES_VERSION=6.5
LIBEDIT_VERSION=20250104-3.1
MAKE_VERSION=4.4
GREP_VERSION=3.12
GAWK_VERSION=5.3.2
LESS_VERSION=668
FILE_VERSION=5.46
DASH_VERSION=0.5.12
LIBPCIACCESS_VERSION=0.18.1
LIBXCRYPT_VERSION=4.4.38
PARTED_VERSION=3.6
DMIDECODE_VERSION=3.6
FINDUTILS_VERSION=4.10.0
IANA_ETC_VERSION=20250612
INETUTILS_VERSION=2.6
WGET_VERSION=1.25.0
PERL_CROSS_VERSION=1.5.3
PERL_VERSION=5.40.2
# Mach, Hurd and Glibc are all taken from the Git repository.

# coreutils
COREUTILS_VERSION=9.7
COREUTILS_SRC=coreutils-$COREUTILS_VERSION
COREUTILS_PKG=$COREUTILS_SRC.tar.xz
COREUTILS_URL=https://ftp.gnu.org/gnu/coreutils/$COREUTILS_PKG

# vim
VIM_VERSION=9.1.1497
VIM_SRC=vim-"$VIM_VERSION"
VIM_PKG=$VIM_SRC.tar.gz
VIM_URL=https://github.com/vim/vim/archive/v$VIM_VERSION/$VIM_PKG

# libunistring
LIBUNISTRING_VERSION=1.3
LIBUNISTRING_SRC=libunistring-$LIBUNISTRING_VERSION
LIBUNISTRING_PKG=$LIBUNISTRING_SRC.tar.xz
LIBUNISTRING_URL=https://ftp.gnu.org/gnu/libunistring/$LIBUNISTRING_PKG

# libidn2
LIBIDN2_VERSION=2.3.7
LIBIDN2_SRC=libidn2-$LIBIDN2_VERSION
LIBIDN2_PKG=$LIBIDN2_SRC.tar.gz
LIBIDN2_URL=https://ftp.gnu.org/gnu/libidn/$LIBIDN2_PKG

# libpsl
LIBPSL_VERSION=0.21.5
LIBPSL_SRC=libpsl-$LIBPSL_VERSION
LIBPSL_PKG=$LIBPSL_SRC.tar.gz
LIBPSL_URL=https://github.com/rockdaboot/libpsl/releases/download/$LIBPSL_VERSION/$LIBPSL_PKG

# curl
CURL_VERSION=8.14.1
CURL_SRC=curl-$CURL_VERSION
CURL_PKG=$CURL_SRC.tar.xz
CURL_URL=https://curl.se/download/$CURL_PKG

# libdaemon
LIBDAEMON_VERSION=0.14
LIBDAEMON_SRC=libdaemon-$LIBDAEMON_VERSION
LIBDAEMON_PKG=$LIBDAEMON_SRC.tar.gz
LIBDAEMON_URL=https://0pointer.de/lennart/projects/libdaemon/$LIBDAEMON_PKG

# ca-certificates
CA_CERTIFICATES_URL=https://salsa.debian.org/debian/ca-certificates.git
CA_CERTIFICATES_SRC=ca-certificates

# git
GIT_VERSION=2.50.1
GIT_SRC=git-$GIT_VERSION
GIT_PKG=$GIT_SRC.tar.xz
GIT_URL=https://www.kernel.org/pub/software/scm/git/$GIT_PKG

# openssl
OPENSSL_VERSION=3.5.1
OPENSSL_SRC=openssl-$OPENSSL_VERSION
OPENSSL_PKG=$OPENSSL_SRC.tar.gz
OPENSSL_URL=https://www.openssl.org/source/$OPENSSL_PKG

# libgpg-error
GPG_ERROR_VERSION=1.55
GPG_ERROR_SRC=libgpg-error-$GPG_ERROR_VERSION
GPG_ERROR_PKG=$GPG_ERROR_SRC.tar.bz2
GPG_ERROR_URL=https://gnupg.org/ftp/gcrypt/libgpg-error/$GPG_ERROR_PKG

# libgcrypt
GCRYPT_VERSION=1.11.1
GCRYPT_SRC=libgcrypt-$GCRYPT_VERSION
GCRYPT_PKG=$GCRYPT_SRC.tar.bz2
GCRYPT_URL=https://gnupg.org/ftp/gcrypt/libgcrypt/$GCRYPT_PKG

# binutils
BINUTILS_VERSION=2.44
BINUTILS_SRC=binutils-$BINUTILS_VERSION
BINUTILS_PKG=$BINUTILS_SRC.tar.bz2
BINUTILS_URL=https://ftp.gnu.org/gnu/binutils/$BINUTILS_PKG

# GCC
GCC_VERSION=15.1.0
GCC_SRC=gcc-$GCC_VERSION
GCC_PKG=$GCC_SRC.tar.xz
GCC_URL=https://ftp.gnu.org/gnu/gcc/gcc-$GCC_VERSION/$GCC_PKG

# parted
PARTED_VERSION=3.6
PARTED_SRC=parted-$PARTED_VERSION
PARTED_PKG=$PARTED_SRC.tar.xz
PARTED_URL=https://ftp.gnu.org/gnu/parted/$PARTED_PKG

# libtirpc
LIBTIRPC_VERSION=1.3.6
LIBTIRPC_SRC=libtirpc-$LIBTIRPC_VERSION
LIBTIRPC_PKG=$LIBTIRPC_SRC.tar.bz2
LIBTIRPC_URL=https://sourceforge.net/projects/libtirpc/files/libtirpc/$LIBTIRPC_VERSION/$LIBTIRPC_PKG

# openssh
OPENSSH_VERSION=10.0p1
OPENSSH_SRC=openssh-$OPENSSH_VERSION
OPENSSH_PKG=$OPENSSH_SRC.tar.gz
OPENSSH_URL=https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/$OPENSSH_PKG

# gawk
GAWK_VERSION=5.3.2
GAWK_SRC=gawk-$GAWK_VERSION
GAWK_PKG=$GAWK_SRC.tar.xz
GAWK_URL=https://ftp.gnu.org/gnu/gawk/$GAWK_PKG

# grub
GRUB_VERSION=2.06
GRUB_SRC=grub-$GRUB_VERSION
GRUB_PKG=$GRUB_SRC.tar.gz
GRUB_URL=https://ftp.gnu.org/gnu/grub/$GRUB_PKG

# htop
HTOP_VERSION=3.3.0
HTOP_SRC=htop-$HTOP_VERSION
HTOP_PKG=$HTOP_SRC.tar.xz
HTOP_URL=https://github.com/htop-dev/htop/releases/download/$HTOP_VERSION/$HTOP_PKG

# bash
BASH_VERSION=5.3
BASH_SRC=bash-$BASH_VERSION
BASH_PKG=$BASH_SRC.tar.gz
BASH_URL=https://ftp.gnu.org/gnu/bash/"$BASH_PKG"

# file
FILE_VERSION=5.46
FILE_SRC=file-$FILE_VERSION
FILE_PKG=$FILE_SRC.tar.gz
FILE_URL=https://fossies.org/linux/misc/$FILE_PKG

# gdb
GDB_SRC=binutils-gdb

# mpfr
MPFR_VERSION=4.2.2
MPFR_SRC=mpfr-$MPFR_VERSION
MPFR_PKG=$MPFR_SRC.tar.bz2
MPFR_URL=http://mpfr.org/mpfr-current/$MPFR_PKG

# libxcrypt
LIBXCRYPT_VERSION=4.4.38
LIBXCRYPT_SRC=libxcrypt-$LIBXCRYPT_VERSION
LIBXCRYPT_PKG=$LIBXCRYPT_SRC.tar.xz
LIBXCRYPT_URL=https://github.com/besser82/libxcrypt/releases/download/v$LIBXCRYPT_VERSION/$LIBXCRYPT_PKG

ISL_VERSION=0.27
ISL_SRC=isl-$ISL_VERSION
ISL_PKG=$ISL_SRC.tar.xz
ISL_URL=https://libisl.sourceforge.io/$ISL_PKG

AUTOCONF_ARCHIVE_VERSION=2024.10.16
AUTOCONF_VERSION=2.72
AUTOMAKE_VERSION=1.18
BISON_VERSION=3.8.2
DIFFUTILS_VERSION=3.12
GZIP_VERSION=1.14
HELP2MAN_VERSION=1.49.3
LIBTOOL_VERSION=2.5.4
M4_VERSION=1.4.20
NINJA_VERSION=1.12.1
PATCH_VERSION=2.8
PKGCONF_VERSION=2.5.1
TAR_VERSION=1.35
TEXINFO_VERSION=7.2
XZ_VERSION=5.8.1

PACMAN_VERSION=6.1.0
MESON_VERSION=1.8.2
PYTHON_MAJOR_VERSION=3.13
PYTHON_VERSION=$PYTHON_MAJOR_VERSION.5
LIBARCHIVE_VERSION=3.8.1
SUDO_VERSION=1.9.17p1
LIBPCAP_VERSION=1.10.5

LIBXKBCOMMON_VERSION=1.10.0
LIBXKBCOMMON_SRC=libxkbcommon-xkbcommon-$LIBXKBCOMMON_VERSION
LIBXKBCOMMON_PKG=xkbcommon-$LIBXKBCOMMON_VERSION.tar.gz
LIBXKBCOMMON_URL=https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/$LIBXKBCOMMON_PKG

XKEYBOARD_CONFIG_VERSION=2.45
LIBXML2_VERSION=v2.14.4
MAKE_VERSION=4.4.1
GETTEXT_VERSION=0.25.1
GPERF_VERSION=3.1
PO4A_VERSION=0.73
READLINE_VERSION=8.3
PERL_INC_LATEST_VERSION=0.500
PERL_POD_PARSER_VERSION=1.67
PERL_POD_PARSER_SRC=Pod-Parser-$PERL_POD_PARSER_VERSION
PERL_POD_PARSER_PKG=$PERL_POD_PARSER_SRC.tar.gz
PERL_POD_PARSER_URL=https://cpan.metacpan.org/authors/id/M/MA/MAREKR/$PERL_POD_PARSER_PKG
PERL_BUILD_VERSION=0.4234
XXHASH_VERSION=0.8.3
RHASH_VERSION=1.4.4
ELFUTILS_VERSION=0.193
DEBUGEDIT_VERSION=5.1
LZ4_VERSION=1.10.0
ZSTD_VERSION=1.5.7
CMAKE_VERSION=4.0.3
LIBSSH2_VERSION=1.11.1
PCRE2_VERSION=10.45
EXPAT_VERSION=2.7.1
EXPAT_TAG_VERSION=2_7_1
JSONCPP_VERSION=1.9.6
LIBUV_VERSION=1.51.0

LIBKSBA_VERSION=1.6.7
LIBKSBA_SRC=libksba-$LIBKSBA_VERSION
LIBKSBA_PKG=$LIBKSBA_SRC.tar.bz2
LIBKSBA_URL=https://www.gnupg.org/ftp/gcrypt/libksba/$LIBKSBA_PKG

LIBASSUAN_VERSION=3.0.1
LIBASSUAN_SRC=libassuan-$LIBASSUAN_VERSION
LIBASSUAN_PKG=$LIBASSUAN_SRC.tar.bz2
LIBASSUAN_URL=https://gnupg.org/ftp/gcrypt/libassuan/$LIBASSUAN_PKG

NPTH_VERSION=1.8
NPTH_SRC=npth-$NPTH_VERSION
NPTH_PKG=$NPTH_SRC.tar.bz2
NPTH_URL=https://gnupg.org/ftp/gcrypt/npth/$NPTH_PKG

GNUPG_VERSION=2.4.8
GNUPG_SRC=gnupg-$GNUPG_VERSION
GNUPG_PKG=$GNUPG_SRC.tar.bz2
GNUPG_URL=https://gnupg.org/ftp/gcrypt/gnupg/$GNUPG_PKG

PUBLICSUFFIX_LIST_SRC=publicsuffix-list

MPDECIMAL_VERSION=4.0.0
MPDECIMAL_SRC=mpdecimal-$MPDECIMAL_VERSION
MPDECIMAL_PKG=$MPDECIMAL_SRC.tar.gz
MPDECIMAL_URL=https://www.bytereef.org/software/mpdecimal/releases/$MPDECIMAL_PKG

TCL_VERSION=8.6.16
TCL_SRC=tcl$TCL_VERSION
TCL_PKG=$TCL_SRC-src.tar.gz
TCL_URL=https://downloads.sourceforge.net/sourceforge/tcl/$TCL_PKG

SQLITE_VERSION=4.50.2
SQLITE_SRCVER=3500200
SQLITE_SRC=sqlite-src-$SQLITE_SRCVER
SQLITE_PKG=$SQLITE_SRC.zip
SQLITE_URL=https://www.sqlite.org/2025/sqlite-src-${SQLITE_SRCVER}.zip

PATCHELF_VERSION=0.18.0
PATCHELF_SRC=patchelf-$PATCHELF_VERSION
PATCHELF_PKG=$PATCHELF_SRC.tar.bz2
PATCHELF_URL=https://github.com/NixOS/patchelf/releases/download/$PATCHELF_VERSION/$PATCHELF_PKG

LIBXSLT_SRC=libxslt
LIBXSLT_URL=https://gitlab.gnome.org/GNOME/libxslt.git

MERCURIAL_VERSION=7.0.2
MERCURIAL_SRC=mercurial-$MERCURIAL_VERSION
MERCURIAL_PKG=$MERCURIAL_SRC.tar.gz
MERCURIAL_URL=https://www.mercurial-scm.org/release/$MERCURIAL_PKG

ASCIIDOC_VERSION=10.2.1
ASCIIDOC_SRC=asciidoc-$ASCIIDOC_VERSION
ASCIIDOC_PKG=$ASCIIDOC_SRC.tar.gz
ASCIIDOC_URL=https://github.com/asciidoc-py/asciidoc-py/releases/download/$ASCIIDOC_VERSION/$ASCIIDOC_PKG

LIBMD_VERSION=1.1.0
LIBMD_SRC=libmd-$LIBMD_VERSION
LIBMD_PKG=$LIBMD_SRC.tar.xz
LIBMD_URL=https://archive.hadrons.org/software/libmd/$LIBMD_PKG

LIBBSD_VERSION=0.12.2
LIBBSD_SRC=libbsd-$LIBBSD_VERSION
LIBBSD_PKG=$LIBBSD_SRC.tar.xz
LIBBSD_URL=https://libbsd.freedesktop.org/releases/$LIBBSD_PKG

LIBFFI_VERSION=3.5.1
LIBFFI_SRC=libffi-$LIBFFI_VERSION
LIBFFI_PKG=$LIBFFI_SRC.tar.gz
LIBFFI_URL=https://github.com/libffi/libffi/releases/download/v$LIBFFI_VERSION/$LIBFFI_PKG

NETTLE_VERSION=3.10.2
NETTLE_SRC=nettle-$NETTLE_VERSION
NETTLE_PKG=$NETTLE_SRC.tar.gz
NETTLE_URL=https://ftp.gnu.org/gnu/nettle/$NETTLE_PKG

LIBTASN1_VERSION=4.20.0
LIBTASN1_SRC=libtasn1-$LIBTASN1_VERSION
LIBTASN1_PKG=$LIBTASN1_SRC.tar.gz
LIBTASN1_URL=https://ftp.gnu.org/gnu/libtasn1/$LIBTASN1_PKG

GNUTLS_MAJOR=3.8
GNUTLS_VERSION=$GNUTLS_MAJOR.9
GNUTLS_SRC=gnutls-$GNUTLS_VERSION
GNUTLS_PKG=$GNUTLS_SRC.tar.xz
GNUTLS_URL=https://www.gnupg.org/ftp/gcrypt/gnutls/v$GNUTLS_MAJOR/$GNUTLS_PKG

GYP_VERSION=20240207.1615ec32
GYP_SRC=gyp-$GYP_VERSION
GYP_URL=https://chromium.googlesource.com/external/gyp

NSPR_VERSION=NSPR_4_36_RTM
NSPR_SRC=nspr-$NSPR_VERSION
NSPR_PKG=$NSPR_VERSION.zip
NSPR_URL=https://hg.mozilla.org/projects/nspr/archive/NSPR_4_36_RTM.zip

PYTHON_SIX_VERSION=1.17.0
PYTHON_SIX_SRC=six-$PYTHON_SIX_VERSION
PYTHON_SIX_PKG=$PYTHON_SIX_SRC.tar.gz
PYTHON_SIX_URL=https://pypi.io/packages/source/s/six/$PYTHON_SIX_PKG

PYTHON_PASSLIB_VERSION=1.7.4
PYTHON_PASSLIB_SRC=passlib-$PYTHON_PASSLIB_VERSION
PYTHON_PASSLIB_PKG=$PYTHON_PASSLIB_SRC.tar.gz
PYTHON_PASSLIB_URL=https://pypi.io/packages/source/p/passlib/$PYTHON_PASSLIB_PKG

ATTR_VERSION=2.5.2
ATTR_SRC=attr-$ATTR_VERSION
ATTR_PKG=$ATTR_SRC.tar.xz
ATTR_URL=https://download.savannah.gnu.org/releases/attr/$ATTR_PKG

NSL_VERSION=2.0.1
NSL_SRC=libnsl-$NSL_VERSION
NSL_PKG=libnsl-v$NSL_VERSION.tar.gz
NSL_URL=https://github.com/thkukuk/libnsl/archive/v$NSL_VERSION/$NSL_PKG
